package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/development-and-dinosaurs/diplodocs/pkg/navigation"
	"github.com/pelletier/go-toml/v2"
)

// Config represents the full diplodocs configuration.
type Config struct {
	Site     SiteConfig                 `toml:"site"`
	Theme    ThemeConfig                `toml:"theme"`
	Features FeaturesConfig             `toml:"features"`
	DocsDir  string                     `toml:"docs_dir"`
	OutDir   string                     `toml:"out_dir"`
	Nav      []navigation.NavItemConfig `toml:"nav,omitempty"`
	ExtraCSS []string                   `toml:"extra_css,omitempty"`
	ExtraJS  []string                   `toml:"extra_javascript,omitempty"`
}

// SiteConfig represents site metadata.
type SiteConfig struct {
	Name        string `toml:"name"`
	Description string `toml:"description"`
	Author      string `toml:"author"`
	RepoURL     string `toml:"repo_url"`
	BaseURL     string `toml:"base_url"`
	Version     string `toml:"version"`
	EditBranch  string `toml:"edit_branch"`
}

// ThemeConfig represents styling and UI preferences.
type ThemeConfig struct {
	Accent   string `toml:"accent"`    // "emerald", "ocean", "amber", "rose", "purple", "slate"
	DarkMode string `toml:"dark_mode"` // "auto", "light", "dark"
	LogoText string `toml:"logo_text"`
}

// FeaturesConfig enables or disables built-in capabilities.
type FeaturesConfig struct {
	Search          bool `toml:"search"`
	Mermaid         bool `toml:"mermaid"`
	CopyButton      bool `toml:"copy_button"`
	LLMsTxt         bool `toml:"llms_txt"`
	Math            bool `toml:"math"`
	RepoStats       bool `toml:"repo_stats"`
	ShowReadingTime bool `toml:"reading_time"`
	ShowEditLink    bool `toml:"edit_link"`
}

func toTitle(s string) string {
	words := strings.Fields(strings.ReplaceAll(s, "-", " "))
	for i, w := range words {
		if len(w) > 0 {
			words[i] = strings.ToUpper(w[:1]) + strings.ToLower(w[1:])
		}
	}
	return strings.Join(words, " ")
}

// DefaultConfig returns a fully-populated Config with sensible defaults.
func DefaultConfig(dirName string) *Config {
	siteName := "Diplodocs"
	if dirName != "" && dirName != "." {
		siteName = toTitle(filepath.Base(dirName))
	}

	return &Config{
		Site: SiteConfig{
			Name:        siteName,
			Description: "Documentation generated by Diplodocs",
			BaseURL:     "/",
			EditBranch:  "main",
		},
		Theme: ThemeConfig{
			Accent:   "emerald",
			DarkMode: "auto",
			LogoText: "🦕 " + siteName,
		},
		Features: FeaturesConfig{
			Search:          true,
			Mermaid:         true,
			CopyButton:      true,
			LLMsTxt:         true,
			Math:            false,
			RepoStats:       true,
			ShowReadingTime: true,
			ShowEditLink:    true,
		},
		DocsDir: "docs",
		OutDir:  "dist",
	}
}

// LoadConfig loads diplodocs.toml if it exists, or returns defaults.
func LoadConfig(projectRoot string) (*Config, error) {
	cfg := DefaultConfig(projectRoot)

	configPath := filepath.Join(projectRoot, "diplodocs.toml")
	data, err := os.ReadFile(configPath)
	if err != nil {
		if os.IsNotExist(err) {
			// Check if mkdocs.yml or mkdocs.yaml exists
			for _, mk := range []string{"mkdocs.yml", "mkdocs.yaml"} {
				mkPath := filepath.Join(projectRoot, mk)
				if _, err := os.Stat(mkPath); err == nil {
					return LoadFromMkDocs(mkPath)
				}
			}
			// Zero-config mode: return defaults
			return cfg, nil
		}
		return nil, fmt.Errorf("reading config %s: %w", configPath, err)
	}

	if err := toml.Unmarshal(data, cfg); err != nil {
		return nil, fmt.Errorf("parsing %s: %w", configPath, err)
	}

	if cfg.DocsDir == "" {
		cfg.DocsDir = "docs"
	}
	if cfg.OutDir == "" {
		cfg.OutDir = "dist"
	}
	if cfg.Site.Name == "" {
		cfg.Site.Name = "Diplodocs"
	}
	if cfg.Theme.Accent == "" {
		cfg.Theme.Accent = "emerald"
	}
	if cfg.Theme.DarkMode == "" {
		cfg.Theme.DarkMode = "auto"
	}
	if cfg.Theme.LogoText == "" {
		cfg.Theme.LogoText = "🦕 " + cfg.Site.Name
	}
	if cfg.Site.EditBranch == "" {
		cfg.Site.EditBranch = "main"
	}

	return cfg, nil
}
